# Generated by Django 2.2.1 on 2019-05-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.FilePathField(null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('durationAvg', models.FloatField(null=True)),
                ('durationMin', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('dateRegistration', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('image', models.FilePathField(null=True)),
                ('password', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnd', models.DateField(null=True)),
                ('dateLastUpdate', models.DateField(null=True)),
                ('dateStart', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
                ('statusOrder', models.IntegerField(null=True)),
                ('AdditionalService', models.ManyToManyField(to='sbiv_mechts.AdditionalService')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('image', models.FilePathField(null=True)),
                ('name', models.TextField(null=True)),
                ('AdditionalService', models.ManyToManyField(to='sbiv_mechts.AdditionalService')),
            ],
        ),
        migrations.CreateModel(
            name='workTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(null=True)),
                ('startTime', models.DateField(null=True)),
                ('statusOrder', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('AdditionalService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.AdditionalService')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField(null=True)),
                ('image', models.FilePathField(null=True)),
                ('dateBirth', models.DateField(null=True)),
                ('dateRegistration', models.DateField(null=True)),
                ('direction', models.TextField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(null=True)),
                ('workTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.workTime')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.FilePathField(null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPay', models.DateField(null=True)),
                ('sumOfPayment', models.FloatField(null=True)),
                ('AdditionalService', models.ManyToManyField(to='sbiv_mechts.AdditionalService')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Client')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Service')),
                ('Tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Tariff')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Payment',
            field=models.ManyToManyField(to='sbiv_mechts.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Service'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Client')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Order')),
            ],
        ),
    ]
