# Generated by Django 2.2.1 on 2019-05-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.FilePathField(null=True)),
                ('desing', models.FilePathField(null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbiv_mechts.Service')),
            ],
        ),
    ]
