# Generated by Django 2.2.1 on 2019-05-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0002_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Service'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Client'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Service'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Service'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Tariff'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Service'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Service'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.workTime'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='AdditionalService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.AdditionalService'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Order'),
        ),
    ]
