# Generated by Django 2.2.1 on 2019-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0003_auto_20190528_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Chip',
            field=models.ManyToManyField(to='sbiv_mechts.Chip'),
        ),
    ]
