# Generated by Django 2.2.1 on 2019-06-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0004_order_chip'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('durationMin', models.FloatField(null=True)),
                ('AdditionalService', models.ManyToManyField(to='sbiv_mechts.AdditionalService')),
            ],
        ),
        migrations.CreateModel(
            name='workSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(null=True)),
                ('startTime', models.DateField(null=True)),
                ('statusOrder', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('AdditionalService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.AdditionalService')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='statusOrder',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='workTime',
        ),
        migrations.DeleteModel(
            name='workTime',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Order'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Worker'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Worker',
            field=models.ManyToManyField(to='sbiv_mechts.Worker'),
        ),
    ]
