# Generated by Django 2.2.1 on 2019-06-03 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0005_auto_20190603_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='AdditionalService',
        ),
        migrations.AddField(
            model_name='schedule',
            name='AdditionalService',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.AdditionalService'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Worker',
        ),
        migrations.AddField(
            model_name='schedule',
            name='Worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Worker'),
            preserve_default=False,
        ),
    ]
