# Generated by Django 2.2.1 on 2019-06-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbiv_mechts', '0006_auto_20190603_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workSchedule',
            new_name='OrderSchedule',
        ),
        migrations.RenameModel(
            old_name='schedule',
            new_name='WorkerPrice',
        ),
        migrations.AddField(
            model_name='comment',
            name='AdditionalService',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.AdditionalService'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='Worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='AdditionalService',
            field=models.ManyToManyField(to='sbiv_mechts.AdditionalService'),
        ),
        migrations.CreateModel(
            name='generalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('FinishDatetime', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
                ('AdditionalService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.AdditionalService')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbiv_mechts.Worker')),
            ],
        ),
    ]
